### ISSUE TITLE
Compatibility with Laravel 5.6?

### ISSUE THREAD

**Issue by websmurf** [PM-Connect/laravel-param-converter#1]
Just a quick question; have your already tested out your extension with laravel 5.6? 
Are there any issues to be expected?

**Comment by jralph** [comment]
We haven't yet I'm afraid, no. I wouldn't expect there to be any issues based on how the param converter hooks into laravel.

It essentially hooks into `setParameter` method on the route. See: https://laravel.com/api/5.6/Illuminate/Routing/Route.html#method_setParameter

**Comment by websmurf** [comment]
Oki, see #3

**Comment by websmurf** [comment]
Thanks, saw that the pull request was merged. Can you release a new version containing these changes?

**Comment by jralph** [comment]
Release 1.1.0 added now! Thanks!
